version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - '80:80'

  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - '5000:5000'
